### ISSUE TITLE
Script breaks when timezone doesn't match timezone in code

### ISSUE THREAD

**Issue by mikeybeck** [mikeybeck/TogglPy#1]
This is fine most of the time, but becomes a problem when daylight savings occurs

**Comment by alternativshik** [comment]
Hi! how to reproduce the bug? I think, I can fix it.

**Comment by mikeybeck** [comment]
Thanks!  At the moment, the timezone is hard coded to +12:00 on lines 260 & 261. 

For me at least, this breaks on 16 September 2017, when it needs to be +13:00.

If I run the script with no parameters this month, the error occurs.  If you're in a location which uses daylight saving, try running the script with a time period which spans the daylight saving transition date.

I presume you must have changed the timezone in the script before running it, unless you're in the same timezone as me?
Please let me know if you can't replicate the bug and I'll look into it further.

**Comment by alternativshik** [comment]
May be, right way for that is using Timezone setting in config?

**Comment by alternativshik** [comment]
Oh, It's just problem with parse date data with strptime

**Comment by mikeybeck** [comment]
I've added a couple of try..catch blocks to fix it.  Not a great solution but good enough for now.
